version: "3.7"
services:
  fluentd:
    # `bash run.sh registry:refresh` to build and push internal fluentd
    image: barklan/fluentd-cto:2.2.1
    environment:
      FLUENTD_HOSTNAME: 'ctopanel.com'
      FLUENTD_HTTP_DUMP_ENDPOINT: http://cto_backend:8080/api/log/input
      FLUENTD_CTO_PROJECT_TOKEN: ${FLUENTD_CTO_PROJECT_TOKEN?Variable not set}
      FLUENTD_CTO_PROJECT_NAME: ${FLUENTD_CTO_PROJECT_NAME?Variable not set}
    ports:
      - 24224:24224
      - 24224:24224/udp
    user: root
    networks:
      - traefik-public
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  erdapp:
    image: barklan/erdapp-backend:rolling
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - erdapp-volume:/app/media
    networks:
      - traefik-public
    logging:
      driver: fluentd
      options:
        tag: docker.support.erdapp-backend
        fluentd-async-connect: "true"
    ports:
      - 8110:8110
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.erdapp-http.rule=Host(`erdapp.${DOMAIN?Variable not set}`)
        - traefik.http.routers.erdapp-http.entrypoints=http
        - traefik.http.routers.erdapp-http.middlewares=https-redirect
        - traefik.http.routers.erdapp-https.rule=Host(`erdapp.${DOMAIN?Variable not set}`)
        - traefik.http.routers.erdapp-https.entrypoints=https
        - traefik.http.routers.erdapp-https.tls=true
        - traefik.http.routers.erdapp-https.tls.certresolver=le
        - traefik.http.services.erdapp.loadbalancer.server.port=8110

volumes:
  erdapp-volume:

networks:
  traefik-public:
    external: true
