version: "3.7"
services:
  redoc:
    image: "redocly/redoc:v2.0.0-rc.59"
    environment:
      - SPEC_URL=https://raw.githubusercontent.com/barklan/cto/main/docs/openapi.yaml
    networks:
      - traefik-public
    # ports:
      # - 4007:4007
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.docs-http.rule=Host(`docs.${DOMAIN?Variable not set}`)
        - traefik.http.routers.docs-http.entrypoints=http
        - traefik.http.routers.docs-http.middlewares=https-redirect
        - traefik.http.routers.docs-https.rule=Host(`docs.${DOMAIN?Variable not set}`)
        - traefik.http.routers.docs-https.entrypoints=https
        - traefik.http.routers.docs-https.tls=true
        - traefik.http.routers.docs-https.tls.certresolver=le
        - traefik.http.services.docs.loadbalancer.server.port=80

networks:
  traefik-public:
    external: true
