version: "3.7"
services:

  traefik:
    profiles: ["extra"]

  frontend:
    profiles: ["extra"]

  backend:
    profiles: ["main"]
    container_name: cto_backend
    networks:
      - traefik-public
    build:
      context: .
      dockerfile: dockerfiles/core.dockerfile
    env_file:
      ./local.env
    environment:
      - CONFIG_ENV=devdocker

  porter:
    profiles: ["main"]
    container_name: cto_porter
    env_file:
      ./local.env
    environment:
      - CONFIG_ENV=devdocker

  db:
    container_name: db
    profiles: ["main", "db"]
    env_file:
      - local.env

  fluentd:
    profiles: ["main"]
    build:
      context: ./dockerfiles/fluentd_cto
      dockerfile: Dockerfile
    container_name: fluend-cto
    networks:
      - traefik-public
    environment:
      FLUENTD_HTTP_DUMP_ENDPOINT: 'http://cto_backend:8080/api/log/input'
      FLUENTD_HOSTNAME: 'stag.nftgallerydev.online'
      FLUENTD_CTO_PROJECT_TOKEN: '12345'
      FLUENTD_CTO_PROJECT_NAME: '0b6badb2-edbe-458c-a6af-df49e393e5fc'
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  flooder:
    profiles: ["main"]
    entrypoint: ["bash", "/entrypoint.local.sh"]
    ports:
      - 8000:8000
    environment:
      - SERVER_NAME=stag.nftgallerydev.online
      - SERVER_HOST=https://stag.nftgallerydev.online/
      - LOCAL_SETUP=false
    build:
      context: ./test/backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: 'false'
        BUILDKIT_INLINE_CACHE: 1
    networks:
      - traefik-public
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.efk.flooder-logger
        fluentd-async-connect: "true"

  pgweb:
    profiles: ["main", "db"]
    restart: on-failure
    networks:
      - traefik-public
    container_name: pgweb
    image: sosedoff/pgweb
    ports:
      - '8081:8081'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app?sslmode=disable

volumes:
  cto-data:
    external: false
