version: "3.7"
services:

  traefik:
    profiles: ["extra"]

  frontend:
    profiles: ["extra"]

  backend:
    container_name: cto
    networks:
      - shared
    build: .
    environment:
      - CONFIG_ENV=devdocker

  fluend:
    build:
      context: ./dockerfiles/fluentd_cto
      dockerfile: Dockerfile
    container_name: fluend-cto
    networks:
      - shared
    environment:
      FLUENTD_HTTP_DUMP_ENDPOINT: 'http://cto:8080/api/log/input'
      FLUENTD_HOSTNAME: 'stag.nftgallerydev.online'
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  flooder:
    entrypoint: ["bash", "/entrypoint.local.sh"]
    ports:
      - 8000:8000
    environment:
      - SERVER_NAME=stag.nftgallerydev.online
      - SERVER_HOST=https://stag.nftgallerydev.online/
      - LOCAL_SETUP=false
    build:
      context: ./test/backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: 'false'
        BUILDKIT_INLINE_CACHE: 1
    networks:
      - shared
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.efk.flooder-logger
        fluentd-async-connect: "true"


volumes:
  cto-data:
    external: false

networks:
  shared:
    external: true
