version: "3.8"
services:

  traefik:
    profiles: ["extra"]

  frontend:
    profiles: ["extra"]

  backend:
    restart: on-failure
    profiles: ["main"]
    container_name: cto_backend
    volumes:
      - ./.cache:/app/data
      - ./.cache/media:/app/media
      - '${PROJECT_PATH-.}/environment:/app/config'
    networks:
      - traefik-public
    env_file:
      ./local.env
    environment:
      - CONFIG_ENV=devdocker

  porter:
    profiles: ["main"]
    container_name: cto_porter
    env_file:
      ./local.env
    environment:
      - CONFIG_ENV=devdocker

  loginput:
    profiles: ["main"]
    container_name: cto_loginput
    env_file:
      ./local.env

  db:
    container_name: db
    profiles: ["main", "db"]
    env_file:
      - local.env

  rabbitmq:
    profiles: ["main", "mq"]
    env_file:
      - local.env

  cache:
    profiles: ["main", "cache"]
    env_file:
      - local.env

  fluentd:
    profiles: ["main"]
    build:
      context: ./dockerfiles/fluentd_cto
      dockerfile: Dockerfile
    container_name: fluend-cto
    networks:
      - traefik-public
    environment:
      FLUENTD_HTTP_DUMP_ENDPOINT: 'http://cto_loginput:8900/api/loginput/fluentd'
      FLUENTD_HOSTNAME: 'stag.nftgallerydev.online'
      FLUENTD_CTO_PROJECT_TOKEN: 'pJUIUOQfkMRJrtfNjFXKxUjnEmgsVBmaDGRcLFgTqyKktKgK'
      FLUENTD_CTO_PROJECT_NAME: 'c8751840-629e-40ea-8cf5-c9d331f5444c'
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  flooder:
    profiles: ["main"]
    entrypoint: ["bash", "/entrypoint.local.sh"]
    ports:
      - 8000:8000
    environment:
      - SERVER_NAME=stag.nftgallerydev.online
      - SERVER_HOST=https://stag.nftgallerydev.online/
      - LOCAL_SETUP=false
    build:
      context: ./test/backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: 'false'
        BUILDKIT_INLINE_CACHE: 1
    networks:
      - traefik-public
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.efk.flooder-logger
        fluentd-async-connect: "true"

  pgweb:
    profiles: ["main", "db"]
    restart: on-failure
    networks:
      - traefik-public
    container_name: pgweb
    image: sosedoff/pgweb
    ports:
      - '8081:8081'
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/app?sslmode=disable

volumes:
  cto-data:
    external: false
