version: "3.7"
services:

  traefik:
    profiles: ["extra"]

  frontend:
    profiles: ["extra"]

  backend:
    container_name: cto
    networks:
      - shared
    build: .
    environment:
      - CONFIG_ENV=devdocker

  fluend:
    build:
      context: ./dockerfiles/fluentd_cto
      dockerfile: Dockerfile
    container_name: fluend-cto
    networks:
      - shared
    environment:
      FLUENTD_HTTP_DUMP_ENDPOINT: 'http://cto:8080/api/log/input'
      FLUENTD_HOSTNAME: 'stag.nftgallerydev.online'
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  flooder:
    image: bash:alpine3.14
    command: bash -c 'for i in {1..10}; do echo "Hey $i! ERROR"; sleep 1; done; exit 0'
    networks:
      - shared
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: docker.stag.flooder-logger
        fluentd-async-connect: "true"


volumes:
  cto-data:
    external: false

networks:
  shared:
    external: true
