// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'AkarIcons:question': typeof import('~icons/akar-icons/question')['default']
    'Bytesize:signIn': typeof import('~icons/bytesize/sign-in')['default']
    'Carbon:aiStatus': typeof import('~icons/carbon/ai-status')['default']
    'Carbon:dataViewAlt': typeof import('~icons/carbon/data-view-alt')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('~icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('~icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('~icons/carbon/logo-github')['default']
    'Codicon:home': typeof import('~icons/codicon/home')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FooterMy: typeof import('./components/FooterMy.vue')['default']
    MenuBar: typeof import('./components/MenuBar.vue')['default']
  }
}

export { }
