// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package porter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PorterClient is the client API for Porter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PorterClient interface {
	TelegramSend(ctx context.Context, in *TelegramSendRequest, opts ...grpc.CallOption) (*TelegramSendReply, error)
}

type porterClient struct {
	cc grpc.ClientConnInterface
}

func NewPorterClient(cc grpc.ClientConnInterface) PorterClient {
	return &porterClient{cc}
}

func (c *porterClient) TelegramSend(ctx context.Context, in *TelegramSendRequest, opts ...grpc.CallOption) (*TelegramSendReply, error) {
	out := new(TelegramSendReply)
	err := c.cc.Invoke(ctx, "/protos.Porter/TelegramSend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PorterServer is the server API for Porter service.
// All implementations must embed UnimplementedPorterServer
// for forward compatibility
type PorterServer interface {
	TelegramSend(context.Context, *TelegramSendRequest) (*TelegramSendReply, error)
	mustEmbedUnimplementedPorterServer()
}

// UnimplementedPorterServer must be embedded to have forward compatible implementations.
type UnimplementedPorterServer struct {
}

func (UnimplementedPorterServer) TelegramSend(context.Context, *TelegramSendRequest) (*TelegramSendReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TelegramSend not implemented")
}
func (UnimplementedPorterServer) mustEmbedUnimplementedPorterServer() {}

// UnsafePorterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PorterServer will
// result in compilation errors.
type UnsafePorterServer interface {
	mustEmbedUnimplementedPorterServer()
}

func RegisterPorterServer(s grpc.ServiceRegistrar, srv PorterServer) {
	s.RegisterService(&Porter_ServiceDesc, srv)
}

func _Porter_TelegramSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TelegramSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PorterServer).TelegramSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Porter/TelegramSend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PorterServer).TelegramSend(ctx, req.(*TelegramSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Porter_ServiceDesc is the grpc.ServiceDesc for Porter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Porter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Porter",
	HandlerType: (*PorterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TelegramSend",
			Handler:    _Porter_TelegramSend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/protos/porter/main.proto",
}
