openapi: 3.0.1
info:
  title: CTO
  description: https://redoc.ly/docs/cli/#.pathspets.yaml
  version: '1.0.1'
  contact:
    name: API Support
    email: example@example.com

servers:
  - url: https://ctopanel.com/api

tags:
  - name: auth
    description: Authentication
  - name: log
    description: Logs
  - name: users
    description: Users

paths:
  /log/input:
    $ref: './paths/input.yml#/FluentdLogInput'
  /log/exact:
    $ref: './paths/getlogs.yml#/LogExact'

components:
  # schemas:
    # Log:
      # $ref: './schemas/Log.yml'
  securitySchemes:
    TokenAuth:
      type: apiKey
      name: Authorization
      in: header
      description: Token-based authentication with required prefix "Token"
    FluentdBasicAuth:
      type: http
      scheme: basic
      description: >
        Fluentd basic auth. Username is project name, password is project secret.
