openapi: 3.1.0
info:
  title: CTO
  description: f
  version: '1.0.1'
  contact:
    name: API Support
    email: example@example.com

servers:
  - url: https://ctopanel.com/api/

tags:
  - name: auth
    description: Authentication
  - name: input
    description: Input
  - name: users
    description: Users

paths:
  /users/followers/:
    get:
      tags:
        - users
      summary: Temp
      responses:
        '200':
          description: 'OK'
        '400':
          description: 'Bad Request'
        '401':
          description: 'Not Authorized'
        '403':
          description: 'Forbidden'
