openapi: 3.1.0
info:
  title: CTO
  description: https://redoc.ly/docs/cli/#.pathspets.yaml
  version: '1.0.1'
  contact:
    name: API Support
    email: example@example.com

servers:
  - url: https://ctopanel.com/api/

tags:
  - name: auth
    description: Authentication
  - name: input
    description: Input
  - name: users
    description: Users

paths:
  /users/followers/:
    $ref: './paths/users/followers.yml#/ListFollowers'

components:
  schemas:
    ListFollowers:
      $ref: './schemas/users/ListFollowers.yml'
  securitySchemes:
    TokenAuth:
      type: apiKey
      name: Authorization
      in: header
      description: Token-based authentication with required prefix "Token"
